### ISSUE TITLE
Cosmetic bullet disappears after piercing through transparent object

### ISSUE THREAD

**Issue by slitherylemur** [XanTheDragon/FastCastAPIDocs#5]
after hitting a pierceable transparent object the ray seems to continue but the bullet stops being visible. 
![problem](https://user-images.githubusercontent.com/67226924/85224480-a9adfa00-b3c2-11ea-9b0b-1d43b2343ced.gif)

would appreciate any help.

thanks, Liam

**Comment by slitherylemur** [comment]
after further investigation I've noticed that the bullet losses its parent after piercing. setting the parts parent to the workspace in the OnRayUpdated function/LengthChanged event fixes the problem. 
I've not figured out why or when the parent was lost

**Comment by EtiTheSpirit** [comment]
Apologies for the late response. I can't get this to happen under stock behavior of the module right now. Please make sure your own code is correctly structured to handle the events for the module. A pretty common mistake a lot of people make is structuring their code incorrectly which results in odd behavior like this.

Since I can't get this issue to occur, I will be closing the issue. Feel free to message me on the developer forums (if you have an account) or reply here if you can't message me should you find yourself unable to fix the issue on your own.
